application: sdkversion
module: default
version: 1
runtime: go
api_version: go1.4beta
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 25

handlers:
- url: /.*
  script: _go_app